"""ServiceNow incident draft and create helpers."""

from __future__ import annotations

import hashlib
import hmac
import json
from datetime import datetime, timezone
from typing import Any

import requests

from .config import Config
from .idempotency import (
    begin_side_effect,
    complete_side_effect_success,
    mark_side_effect_uncertain,
)
from .runtime_security import validate_https_url

_SHORT_DESCRIPTION_MAX_CHARS = 160
_DESCRIPTION_MAX_CHARS = 4000
_WORK_NOTES_MAX_CHARS = 4000


def _truncate(value: str, max_chars: int) -> str:
    text = str(value or "").strip()
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 3].rstrip() + "..."


def _build_short_description(llm_response: dict[str, Any]) -> str:
    alert_reconciliation = llm_response.get("alert_reconciliation", {})
    if not isinstance(alert_reconciliation, dict):
        alert_reconciliation = {}
    summary = str(alert_reconciliation.get("one_sentence_summary", "")).strip()
    verdict = str(alert_reconciliation.get("verdict", "")).strip()
    if summary:
        return _truncate(summary, _SHORT_DESCRIPTION_MAX_CHARS)
    if verdict:
        return _truncate(f"Notable analysis: {verdict}", _SHORT_DESCRIPTION_MAX_CHARS)
    return "Notable analysis requires triage"


def _build_description(llm_response: dict[str, Any]) -> str:
    alert_reconciliation = llm_response.get("alert_reconciliation", {})
    if not isinstance(alert_reconciliation, dict):
        alert_reconciliation = {}

    decision_drivers = alert_reconciliation.get("decision_drivers", [])
    if not isinstance(decision_drivers, list):
        decision_drivers = []
    recommended_actions = alert_reconciliation.get("recommended_actions", [])
    if not isinstance(recommended_actions, list):
        recommended_actions = []

    section = llm_response.get("query_result_section", {})
    summary = section.get("summary", {}) if isinstance(section, dict) else {}
    if not isinstance(summary, dict):
        summary = {}

    description_lines = [
        "Generated by AWS notable analyzer.",
        f"Verdict: {str(alert_reconciliation.get('verdict', 'unknown')).strip() or 'unknown'}",
        f"Confidence: {str(alert_reconciliation.get('confidence', 'unknown')).strip() or 'unknown'}",
        f"Summary: {str(alert_reconciliation.get('one_sentence_summary', 'unknown')).strip() or 'unknown'}",
    ]
    if decision_drivers:
        description_lines.append("Decision drivers:")
        description_lines.extend(f"- {str(item).strip()}" for item in decision_drivers if str(item).strip())
    if recommended_actions:
        description_lines.append("Recommended actions:")
        description_lines.extend(
            f"- {str(item).strip()}" for item in recommended_actions if str(item).strip()
        )
    if summary:
        description_lines.append(
            "Query results summary: "
            f"attempted={int(summary.get('attempted', 0) or 0)}, "
            f"executed={int(summary.get('executed', 0) or 0)}, "
            f"denied={int(summary.get('denied', 0) or 0)}, "
            f"failed={int(summary.get('failed', 0) or 0)}, "
            f"skipped={int(summary.get('skipped', 0) or 0)}"
        )

    return _truncate("\n".join(description_lines), _DESCRIPTION_MAX_CHARS)


def _build_work_notes(*, notable_id: str, finding_id: str) -> str:
    generated_at = datetime.now(timezone.utc).isoformat()
    note = (
        "Generated by AWS notable analyzer\n"
        f"notable_id={notable_id}\n"
        f"finding_id={finding_id}\n"
        f"generated_at={generated_at}"
    )
    return _truncate(note, _WORK_NOTES_MAX_CHARS)


def build_servicenow_incident_draft(
    llm_response: dict[str, Any],
    *,
    config: Config,
    notable_id: str,
    finding_id: str,
) -> dict[str, Any]:
    """Build a ServiceNow incident draft payload from analysis output."""

    if not bool(getattr(config, "SERVICENOW_DRAFT_ENABLED", False)):
        return {
            "status": "skipped",
            "operation": "draft",
            "message": "ServiceNow draft is disabled",
        }

    assignment_group = str(getattr(config, "SERVICENOW_ASSIGNMENT_GROUP", "")).strip()
    if not assignment_group:
        return {
            "status": "error",
            "operation": "draft",
            "message": "ServiceNow assignment group is required when draft is enabled",
        }

    draft = {
        "short_description": _build_short_description(llm_response),
        "description": _build_description(llm_response),
        "assignment_group": assignment_group,
        "category": "security",
        "subcategory": "analysis",
        "impact": "2",
        "urgency": "2",
        "correlation_id": finding_id or notable_id,
        "correlation_display": notable_id,
        "work_notes": _build_work_notes(notable_id=notable_id, finding_id=finding_id),
    }
    return {
        "status": "success",
        "operation": "draft",
        "incident_payload": draft,
        "message": "ServiceNow draft created",
    }


def extract_servicenow_create_approval(alert_payload: Any) -> dict[str, Any]:
    """Extract payload-level ServiceNow approval metadata."""

    if not isinstance(alert_payload, dict):
        return {}
    approval = alert_payload.get("servicenow_create_approval", {})
    if not isinstance(approval, dict):
        return {}
    return {
        "approved": approval.get("approved"),
        "approved_by": str(approval.get("approved_by", "")).strip(),
        "approval_ref": str(approval.get("approval_ref", "")).strip(),
        "approved_at": str(approval.get("approved_at", "")).strip(),
        "signature": str(approval.get("signature", "")).strip(),
    }


def _approval_signature_payload(
    approval: dict[str, Any],
    *,
    correlation_id: str,
) -> str:
    """Build the canonical approval payload signed by a trusted approval service."""

    return json.dumps(
        {
            "approved": approval.get("approved"),
            "approved_by": str(approval.get("approved_by", "")).strip(),
            "approval_ref": str(approval.get("approval_ref", "")).strip(),
            "approved_at": str(approval.get("approved_at", "")).strip(),
            "correlation_id": correlation_id,
        },
        ensure_ascii=True,
        sort_keys=True,
        separators=(",", ":"),
    )


def _validate_create_approval(
    approval: dict[str, Any],
    *,
    require_approval: bool,
    correlation_id: str,
    approval_hmac_key: str,
) -> tuple[bool, str]:
    if not require_approval:
        return True, ""
    if not isinstance(approval, dict) or approval.get("approved") is not True:
        return False, "ServiceNow create denied: explicit approval is required"
    approved_by = str(approval.get("approved_by", "")).strip()
    if not approved_by:
        return False, "ServiceNow create denied: approved_by is required"
    if not approval_hmac_key:
        return False, "ServiceNow create denied: trusted approval signature key is required"
    signature = str(approval.get("signature", "")).strip()
    if not signature:
        return False, "ServiceNow create denied: approval signature is required"
    expected = hmac.new(
        approval_hmac_key.encode("utf-8"),
        _approval_signature_payload(approval, correlation_id=correlation_id).encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
    if not hmac.compare_digest(signature, expected):
        return False, "ServiceNow create denied: approval signature is invalid"
    return True, ""


def create_servicenow_incident(
    draft_payload: dict[str, Any],
    *,
    config: Config,
    api_token: str,
    approval: dict[str, Any] | None = None,
    approval_hmac_key: str = "",
    idempotency_client: Any | None = None,
) -> dict[str, Any]:
    """Create a ServiceNow incident from an approved draft payload."""

    if not bool(getattr(config, "SERVICENOW_CREATE_ENABLED", False)):
        return {
            "status": "skipped",
            "operation": "create",
            "message": "ServiceNow create is disabled",
        }

    base_url = str(getattr(config, "SERVICENOW_BASE_URL", "")).strip()
    path = str(getattr(config, "SERVICENOW_CREATE_PATH", "")).strip()
    timeout_seconds = int(getattr(config, "SERVICENOW_TIMEOUT_SECONDS", 15))
    idempotency_key = str(
        draft_payload.get("correlation_id") or draft_payload.get("correlation_display") or ""
    ).strip()

    allowed, reason = _validate_create_approval(
        approval or {},
        require_approval=bool(getattr(config, "SERVICENOW_CREATE_REQUIRES_APPROVAL", True)),
        correlation_id=idempotency_key,
        approval_hmac_key=approval_hmac_key,
    )
    if not allowed:
        return {"status": "denied", "operation": "create", "message": reason, "approval": approval or {}}

    try:
        base_url = validate_https_url(
            base_url,
            setting_name="SERVICENOW_BASE_URL",
            allow_private=bool(getattr(config, "ALLOW_PRIVATE_OUTBOUND_ENDPOINTS", False)),
        )
    except ValueError as exc:
        return {
            "status": "error",
            "operation": "create",
            "message": str(exc),
            "approval": approval or {},
        }
    if not path or not path.startswith("/"):
        return {
            "status": "error",
            "operation": "create",
            "message": "ServiceNow create path must start with '/'",
            "approval": approval or {},
        }
    if not api_token:
        return {
            "status": "error",
            "operation": "create",
            "message": "ServiceNow API token is required",
            "approval": approval or {},
        }

    try:
        reservation = begin_side_effect(
            config,
            operation="servicenow_incident_create",
            key=idempotency_key,
            client=idempotency_client,
        )
    except (ValueError, RuntimeError) as exc:
        return {"status": "error", "operation": "create", "message": str(exc), "approval": approval or {}}

    if not reservation.should_execute:
        metadata = (reservation.existing_marker or {}).get("metadata", {})
        marker_metadata = metadata if isinstance(metadata, dict) else {}
        marker_status = (reservation.existing_marker or {}).get("status", "unknown")
        return {
            "status": "skipped",
            "operation": "create",
            "message": f"ServiceNow incident create already reserved with status={marker_status}",
            "sys_id": str(marker_metadata.get("sys_id", "")).strip(),
            "number": str(marker_metadata.get("number", "")).strip(),
            "idempotency_status": marker_status,
            "approval": approval or {},
        }

    url = f"{base_url.rstrip('/')}{path}"
    headers = {"Authorization": f"Bearer {api_token}", "Content-Type": "application/json"}
    try:
        response = requests.post(
            url,
            json=draft_payload,
            headers=headers,
            timeout=timeout_seconds,
            verify=True,
        )
        response.raise_for_status()
        try:
            body = response.json()
        except ValueError:
            body = {}
        result = body.get("result", {}) if isinstance(body, dict) else {}
        if not isinstance(result, dict):
            result = {}
        result_payload = {
            "status": "success",
            "operation": "create",
            "sys_id": str(result.get("sys_id", "")).strip(),
            "number": str(result.get("number", "")).strip(),
            "message": "ServiceNow incident created",
            "approval": approval or {},
        }
        idempotency_recorded = complete_side_effect_success(
            reservation,
            metadata={"sys_id": result_payload["sys_id"], "number": result_payload["number"]},
        )
        if reservation.enabled:
            result_payload["idempotency_recorded"] = idempotency_recorded
            if not idempotency_recorded:
                result_payload["status"] = "uncertain"
                result_payload["idempotency_status"] = "uncertain"
                result_payload["idempotency_warning"] = (
                    "external incident may have been created; marker reconciliation is required"
                )
        return result_payload
    except requests.RequestException as exc:
        marker_recorded = mark_side_effect_uncertain(
            reservation,
            metadata={
                "external_success": "unknown",
                "uncertain_reason": "servicenow_request_outcome_unknown",
            },
        )
        return {
            "status": "uncertain",
            "operation": "create",
            "message": str(exc),
            "idempotency_status": "uncertain" if marker_recorded else "marker_write_failed",
            "approval": approval or {},
        }
