import unittest
from unittest.mock import MagicMock, patch

import requests

from llm_notable_analysis_onprem_systemd.onprem_service.config import Config
from llm_notable_analysis_onprem_systemd.onprem_service.servicenow import (
    build_servicenow_incident_draft,
    create_servicenow_incident,
    extract_servicenow_create_approval,
)


def _base_llm_response() -> dict:
    return {
        "alert_reconciliation": {
            "verdict": "likely malicious",
            "confidence": "0.82",
            "one_sentence_summary": "Potential credential misuse detected.",
            "decision_drivers": ["failed logins then success"],
            "recommended_actions": ["disable account", "force reset"],
        },
        "query_result_section": {
            "summary": {"attempted": 2, "executed": 1, "denied": 1, "failed": 0, "skipped": 0}
        },
    }


class TestServiceNowAdapter(unittest.TestCase):
    def test_build_draft_success(self) -> None:
        config = Config(
            SERVICENOW_DRAFT_ENABLED=True,
            SERVICENOW_ASSIGNMENT_GROUP="SOC Tier 1",
        )
        result = build_servicenow_incident_draft(
            _base_llm_response(),
            config=config,
            notable_id="notable-1",
            finding_id="finding-1",
        )
        self.assertEqual(result["status"], "success")
        payload = result["incident_payload"]
        self.assertEqual(payload["assignment_group"], "SOC Tier 1")
        self.assertEqual(payload["correlation_id"], "finding-1")
        self.assertIn("Generated by on-prem notable analyzer", payload["description"])

    def test_build_draft_requires_assignment_group(self) -> None:
        config = Config(SERVICENOW_DRAFT_ENABLED=True, SERVICENOW_ASSIGNMENT_GROUP="")
        result = build_servicenow_incident_draft(
            _base_llm_response(),
            config=config,
            notable_id="notable-1",
            finding_id="finding-1",
        )
        self.assertEqual(result["status"], "error")
        self.assertIn("assignment group", result["message"])

    def test_extract_create_approval(self) -> None:
        payload = {
            "servicenow_create_approval": {
                "approved": True,
                "approved_by": "analyst@example.com",
                "approval_ref": "SNOW-1",
                "approved_at": "2026-01-01T00:00:00Z",
            }
        }
        approval = extract_servicenow_create_approval(payload)
        self.assertTrue(approval["approved"])
        self.assertEqual(approval["approved_by"], "analyst@example.com")
        self.assertEqual(approval["approval_ref"], "SNOW-1")

    def test_create_denied_without_required_approval(self) -> None:
        config = Config(
            SERVICENOW_CREATE_ENABLED=True,
            SERVICENOW_CREATE_REQUIRES_APPROVAL=True,
            SERVICENOW_BASE_URL="https://example.service-now.com",
            SERVICENOW_API_TOKEN="token",
            SERVICENOW_CREATE_PATH="/api/now/table/incident",
        )
        result = create_servicenow_incident(
            {"short_description": "x"},
            config=config,
            approval={},
        )
        self.assertEqual(result["status"], "denied")
        self.assertIn("approval", result["message"].lower())

    def test_create_errors_on_non_https_base_url(self) -> None:
        config = Config(
            SERVICENOW_CREATE_ENABLED=True,
            SERVICENOW_CREATE_REQUIRES_APPROVAL=False,
            SERVICENOW_BASE_URL="http://example.service-now.com",
            SERVICENOW_API_TOKEN="token",
            SERVICENOW_CREATE_PATH="/api/now/table/incident",
        )
        result = create_servicenow_incident(
            {"short_description": "x"},
            config=config,
            approval={},
        )
        self.assertEqual(result["status"], "error")
        self.assertIn("HTTPS", result["message"])

    @patch("llm_notable_analysis_onprem_systemd.onprem_service.servicenow.requests.post")
    def test_create_success_normalizes_response(self, mock_post: MagicMock) -> None:
        response = MagicMock()
        response.raise_for_status.return_value = None
        response.json.return_value = {"result": {"sys_id": "abc123", "number": "INC001"}}
        mock_post.return_value = response
        config = Config(
            SERVICENOW_CREATE_ENABLED=True,
            SERVICENOW_CREATE_REQUIRES_APPROVAL=True,
            SERVICENOW_BASE_URL="https://example.service-now.com",
            SERVICENOW_API_TOKEN="token",
            SERVICENOW_CREATE_PATH="/api/now/table/incident",
            SERVICENOW_TIMEOUT_SECONDS=12,
        )
        result = create_servicenow_incident(
            {"short_description": "x"},
            config=config,
            approval={"approved": True, "approved_by": "analyst@example.com"},
        )
        self.assertEqual(result["status"], "success")
        self.assertEqual(result["sys_id"], "abc123")
        self.assertEqual(result["number"], "INC001")
        _, kwargs = mock_post.call_args
        self.assertEqual(kwargs["timeout"], 12)

    @patch(
        "llm_notable_analysis_onprem_systemd.onprem_service.servicenow.requests.post",
        side_effect=requests.RequestException("servicenow down"),
    )
    def test_create_handles_request_exception(self, _mock_post: MagicMock) -> None:
        config = Config(
            SERVICENOW_CREATE_ENABLED=True,
            SERVICENOW_CREATE_REQUIRES_APPROVAL=False,
            SERVICENOW_BASE_URL="https://example.service-now.com",
            SERVICENOW_API_TOKEN="token",
            SERVICENOW_CREATE_PATH="/api/now/table/incident",
        )
        result = create_servicenow_incident(
            {"short_description": "x"},
            config=config,
            approval={},
        )
        self.assertEqual(result["status"], "error")
        self.assertIn("servicenow down", result["message"])


if __name__ == "__main__":
    unittest.main()
