#!/usr/bin/env python3
"""
Generate a markdown report of TODO/FIXME items in this folder.

Design goals:
- No dependencies (stdlib only)
- Exclude node_modules/ and other generated dirs
- Stable, readable output grouped by file
"""

from __future__ import annotations

import argparse
import datetime as _dt
import os
import re
from pathlib import Path
from typing import Iterable, List, Tuple


DEFAULT_EXCLUDE_DIRS = {
    "node_modules",
    "__pycache__",
    ".aws-sam",
    ".git",
    ".venv",
    "venv",
    "ENV",
    "env",
    "dist",
    "build",
}

DEFAULT_INCLUDE_EXTS = {".py", ".md", ".yaml", ".yml", ".mmd"}

MARKERS = ("TODO:", "FIXME:")

# Note: don't use \b around "TODO:" because ":" is non-word; use a conservative non-word-prefix check instead.
_MARKER_RE = re.compile(r"(?<!\w)(?:TODO:|FIXME:)")


def _is_actionable_marker_line(path: Path, line: str) -> bool:
    """
    Return True if `line` contains a TODO/FIXME marker in a comment-like context.

    This avoids false positives like string literals (e.g., MARKERS = ("TODO:", "FIXME:")).
    """
    s = line.rstrip("\n")
    ext = path.suffix.lower()

    # Fast reject
    if not _MARKER_RE.search(s):
        return False

    # Python / YAML: accept comment markers anywhere in the line (inline comments included).
    if ext in {".py", ".yaml", ".yml"}:
        # e.g. "# TODO ..." or "x = 1  # TODO ..."
        return bool(re.search(r"#\s*(TODO:|FIXME:)", s))

    # Mermaid (.mmd): accept Mermaid comments (%% ...)
    if ext == ".mmd":
        return bool(re.search(r"%%\s*(TODO:|FIXME:)", s))

    # Markdown: accept standalone actionable markers (not arbitrary prose).
    if ext == ".md":
        # e.g. "TODO: ..." or "- TODO: ..." / "* FIXME: ..."
        return bool(re.match(r"^\s*(?:[-*]\s*)?(TODO:|FIXME:)", s))

    # Fallback: only count if the marker appears at line start (conservative).
    return bool(re.match(r"^\s*(TODO:|FIXME:)", s))


def _iter_files(
    root: Path,
    include_exts: set[str],
    exclude_dirs: set[str],
    exclude_files: set[Path],
) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(root):
        # prune excluded directories in-place
        dirnames[:] = [d for d in dirnames if d not in exclude_dirs]
        for name in filenames:
            p = Path(dirpath) / name
            try:
                if p.resolve() in exclude_files:
                    continue
            except OSError:
                # If we can't resolve (permissions, transient FS), fall back to including.
                pass
            if p.suffix.lower() in include_exts:
                yield p


def _extract_items(path: Path) -> List[Tuple[int, str]]:
    items: List[Tuple[int, str]] = []
    try:
        # utf-8 with replacement keeps the report resilient
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return items

    for i, line in enumerate(text.splitlines(), start=1):
        if _is_actionable_marker_line(path, line):
            items.append((i, line.rstrip()))
    return items


def build_report(root: Path, include_exts: set[str], exclude_dirs: set[str], exclude_files: set[Path]) -> str:
    collected: List[Tuple[Path, int, str]] = []
    for p in sorted(_iter_files(root, include_exts, exclude_dirs, exclude_files)):
        for line_no, line in _extract_items(p):
            collected.append((p, line_no, line))

    rel_root = root.resolve()
    now = _dt.datetime.now().isoformat(timespec="seconds")

    lines: List[str] = []
    lines.append("# s3_notable_pipeline TODO Report\n")
    lines.append(f"_Generated: {now}_\n")
    lines.append("This file is generated by `tools/todo_report.py`.\n")

    if not collected:
        lines.append("No TODO/FIXME items found.\n")
        return "\n".join(lines)

    # group by file
    current_file: Path | None = None
    for p, line_no, line in collected:
        rel = p.resolve().relative_to(rel_root).as_posix()
        if current_file != p:
            if current_file is not None:
                lines.append("")  # blank line between files
            lines.append(f"## `{rel}`\n")
            current_file = p

        # Normalize leading comment markers for readability
        cleaned = line.strip()
        lines.append(f"- L{line_no}: {cleaned}")

    lines.append("")  # trailing newline
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a markdown TODO/FIXME report for s3_notable_pipeline.")
    parser.add_argument(
        "--root",
        default=str(Path(__file__).resolve().parents[1]),
        help="Root directory to scan (defaults to s3_notable_pipeline/).",
    )
    parser.add_argument(
        "--output",
        default="TODOS.md",
        help="Output markdown path (relative to root unless absolute). Default: TODOS.md",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write the report to --output. If omitted, prints to stdout.",
    )
    args = parser.parse_args()

    root = Path(args.root).resolve()
    # Exclude the output file itself to avoid self-referential TODOs.
    out = Path(args.output)
    if not out.is_absolute():
        out = root / out
    exclude_files = {out.resolve()} if args.write else set()

    report = build_report(
        root=root,
        include_exts=DEFAULT_INCLUDE_EXTS,
        exclude_dirs=DEFAULT_EXCLUDE_DIRS,
        exclude_files=exclude_files,
    )

    if args.write:
        out.write_text(report, encoding="utf-8")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


